from tests.fixtures.mockups import (
    fp_variables,
    pfv_variables,
    pex_handler_variables,
    pex_variables,
    tangible_bv_variables,
    compute_tangible_bvps,
    dct_tangible_bv_variables,
    compute_dct_tangible_bvps,
    pe_ratio_variables,
    de_ratio_variables,
    date_range_variables,
    reporting_date_variables,
    price_hist_variables,
    reporting_date_price_variables,
    income_stmt_response_mock,
)
